/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        'sm': '576px',
        'md': '768px',
        'lg': '992px',
        'xl': '1200px',
      },
      backgroundImage: {
        'artist-hover-1': "url('/public/images/1_hover.png')",
        'artist-hover-2': "url('/public/images/2_hover.png')",
        'artist-hover-3': "url('/public/images/3_hover.png')",
        'artist-hover-4': "url('/public/images/4_hover.png')",
        'artist-hover-5': "url('/public/images/5_hover.png')",
        'artist-hover-6': "url('/public/images/6_hover.png')",
        'artist-hover-7': "url('/public/images/7_hover.png')",
        'artist-hover-8': "url('/public/images/8_hover.png')",
        'artist-hover-9': "url('/public/images/9_hover.png')",
        'artist-hover-10': "url('/public/images/10_hover.png')",
        'artist-hover-11': "url('/public/images/11_hover.png')",
        'artist-hover-12': "url('/public/images/12_hover.png')",
        'artist-hover-13': "url('/public/images/13_hover.png')",
        'artist-hover-14': "url('/public/images/14_hover.png')",
        'artist-default-1': "url('/public/images/1_default.png')",
        'artist-default-2': "url('/public/images/2_default.png')",
        'artist-default-3': "url('/public/images/3_default.png')",
        'artist-default-4': "url('/public/images/4_default.png')",
        'artist-default-5': "url('/public/images/5_default.png')",
        'artist-default-6': "url('/public/images/6_default.png')",
        'artist-default-7': "url('/public/images/7_default.png')",
        'artist-default-8': "url('/public/images/8_default.png')",
        'artist-default-9': "url('/public/images/9_default.png')",
        'artist-default-10': "url('/public/images/10_default.png')",
        'artist-default-11': "url('/public/images/11_default.png')",
        'artist-default-12': "url('/public/images/12_default.png')",
        'artist-default-13': "url('/public/images/13_default.png')",
        'artist-default-14': "url('/public/images/14_default.png')",
        'artist-selected-1': "url('/public/images/1_selected.png')",
        'artist-selected-2': "url('/public/images/2_selected.jpg')",
        'artist-selected-3': "url('/public/images/3_selected.png')",
        'artist-selected-4': "url('/public/images/4_selected.png')",
        'artist-selected-5': "url('/public/images/5_selected.png')",
        'artist-selected-6': "url('/public/images/6_selected.jpg')",
        'artist-selected-7': "url('/public/images/7_selected.png')",
        'artist-selected-8': "url('/public/images/8_selected.png')",
        'artist-selected-9': "url('/public/images/9_selected.png')",
        'artist-selected-10': "url('/public/images/10_selected.png')",
        'artist-selected-11': "url('/public/images/11_selected.png')",
        'artist-selected-12': "url('/public/images/12_selected.png')",
        'artist-selected-13': "url('/public/images/13_selected.png')",
        'artist-selected-14': "url('/public/images/14_selected.png')"
      }
    },
  },
  plugins: [],
}